
version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest                             # 镜像`nacos/nacos-server:latest`
    container_name: nacos_server                                 # 容器名为'nacos_server'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - nacoslog:/home/nacos/logs
      - ./nacos_mysql/init.d/custom.properties:/home/nacos/init.d/custom.properties:ro
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      - PREFER_HOST_MODE=hostname
      - MODE=standalone                           # 单机模式启动
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql   # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
      - MYSQL_SERVICE_DB_NAME=nacos_config      # 所需sql脚本位于 `nacos-mysql/nacos-mysql.sql`
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    depends_on:
      - mysql
    ports:                              # 映射端口
      - "8848:8848"
    networks:
      - localdev

  mysql:
    image: mysql:5.7  # 原镜像`mysql:5.7`
    container_name: mysql5.7                                        # 容器名为'mysql'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - mysqldata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./nacos_mysql/nacos-mysql.sql:/docker-entrypoint-initdb.d/1.sql #mysql初始化 naocos 数据表结构
      - mysqllog:/var/log/mysql
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root         # 设置root用户密码
      MYSQL_DATABASE: demo              # 初始化的数据库名称
    ports:                              # 映射端口
      - "3306:3306"
    networks:
      - localdev

  sentinel:
    image: bladex/sentinel-dashboard                             # 镜像`bladex/sentinel-dashboard`
    container_name: sentinel                                     # 容器名为'sentinel'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    environment:                                                 # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      # 映射端口
      - "8858:8858"
    networks:
      - localdev

  # rabbitmq:
  #   image: rabbitmq:3-management        # 镜像`rabbitmq:3-management` 【 注：该版本包含了web控制页面 】
  #   container_name: rabbitmq            # 容器名为'rabbitmq'
  #   hostname: rabbitmq
  #   restart: always                     # 指定容器退出后的重启策略为始终重启
  #   environment:                        # 设置环境变量,相当于docker run命令中的-e
  #     TZ: Asia/Shanghai
  #     LANG: en_US.UTF-8
  #     RABBITMQ_DEFAULT_VHOST: my_vhost  # 主机名
  #     RABBITMQ_DEFAULT_USER: admin      # 登录账号
  #     RABBITMQ_DEFAULT_PASS: admin      # 登录密码
  #   volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
  #     - rabbitmqdata:/var/lib/rabbitmq
  #   ports:                              # 映射端口
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - localdev

volumes:
  # rabbitmqdata:
  #   name: rabbitmqdata
  #   driver: local
  mysqldata:
    name: mysqldata
    driver: local
  mysqllog:
    driver: local
    name: mysqllog
  nacoslog:
    driver: local
    name: nacoslog


networks:
  localdev:
    name: localdev
    # external: true
    driver: bridge