version: '3.7'

services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    # hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['redirect_http_to_https'] = true
    ports:
      - "2222:22"
      - "8800:80"
      - "8443:443"
    networks:
      - localdev
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - "./gitlabce:/var/log/gitrepo"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  localdev:
    name: localdev
    external: true

volumes:
  gitlab-config:
    name: gitlab-config
    external: true
  gitlab-logs:
    name: gitlab-logs
    external: true
  gitlab-data:
    name: gitlab-data
    external: true